DROP TABLE IF EXISTS events_comments;

CREATE TABLE IF NOT EXISTS events_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_id BIGINT,
    user_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_event_comment PRIMARY KEY (id)
);